/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdditionalInformation: typeof import('./src/shared/components/AdditionalInformation.vue')['default']
    AkCirclePlus: typeof import('@kalimahapps/vue-icons/ak')['AkCirclePlus']
    AnOutlinedPrinter: typeof import('@kalimahapps/vue-icons/an')['AnOutlinedPrinter']
    AnswerPrintPage: typeof import('./src/components/AnswerPrintPage.vue')['default']
    BsArrowDownCircle: typeof import('@kalimahapps/vue-icons/bs')['BsArrowDownCircle']
    BsArrowUpCircle: typeof import('@kalimahapps/vue-icons/bs')['BsArrowUpCircle']
    Button: typeof import('primevue/button')['default']
    CaDocumentAttachment: typeof import('@kalimahapps/vue-icons/ca')['CaDocumentAttachment']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClFilter: typeof import('@kalimahapps/vue-icons/cl')['ClFilter']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Documents: typeof import('./src/components/Documents.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FieldName: typeof import('./src/components/FieldName.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FilterDialog: typeof import('./src/components/FilterDialog.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    GridContainer2Col: typeof import('./src/components/GridContainer2Col.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LeftMenu: typeof import('./src/components/menu/LeftMenu.vue')['default']
    MainHeader: typeof import('./src/components/layouts/MainHeader.vue')['default']
    McRefresh2Fill: typeof import('@kalimahapps/vue-icons/mc')['McRefresh2Fill']
    MenuBlock: typeof import('./src/components/menu/MenuBlock.vue')['default']
    Message: typeof import('./src/components/messages/Message.vue')['default']
    MessageDataTable: typeof import('./src/components/messages/MessageDataTable.vue')['default']
    MessageV6: typeof import('./src/components/messages/MessageV6.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NotificationAnswerPrintPage: typeof import('./src/components/NotificationAnswerPrintPage.vue')['default']
    NotificationInformationPrintPage: typeof import('./src/components/NotificationInformationPrintPage.vue')['default']
    OCalendar: typeof import('./src/components/o-components/OCalendar.vue')['default']
    OInputNumber: typeof import('./src/components/o-components/OInputNumber.vue')['default']
    Password: typeof import('primevue/password')['default']
    PrintPage: typeof import('./src/components/PrintPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TablePageBase: typeof import('./src/components/layouts/TablePageBase.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TopMenu: typeof import('./src/components/menu/TopMenu.vue')['default']
  }
}
